
 server {
     listen 8080;
     server_name localhost;
     root ./www/html;
     index index.html index.htm;
     client_max_body_size 2M;

     error_page 400 /html_error/400.html;
     error_page 403 /html_error/403.html;
     error_page 404 /html_error/404.html;
     error_page 405 /html_error/405.html;
     error_page 408 /html_error/408.html;
     error_page 411 /html_error/411.html;
     error_page 413 /html_error/413.html;
     error_page 415 /html_error/415.html;
     error_page 500 /html_error/500.html;
     error_page 501 /html_error/501.html;
     error_page 502 /html_error/502.html;
     error_page 504 /html_error/504.html;
     error_page 505 /html_error/505.html;

     location / {
         root ./www;
         index index.html;
         allow_methods  GET POST DELETE;
     }
     location /html_error/ {
         root ./www;
     }
     location /images/ {
         root ./www;
         client_max_body_size 1k;
         autoindex on; //directory listing
     }
     location /cgi-bin/ {
         root ./www;
         cgi .py;
         cgi .sh;
     }
     location /upload/ {
         client_max_body_size 500K;
         root ./www;
         autoindex on;
         allow_methods GET POST DELETE;
     }
     location /redirection/ {
         return 301 https://42.fr/en/homepage/;
     }
     location /readonly/ {
        root ./www;
        allow_methods GET;
     }
     location /oldplace/ {
        return 302 /newplace/;
     }
     location /newplace/ {
        root ./www;
        index index.html;
        allow_methods GET;
     }
 }

server {
    listen 127.0.0.1:9080;
    server_name localhost;
    root ./www/html;
    index index.html index.htm;
    client_max_body_size 2M;

    error_page 400 /html_error/400.html;
    error_page 403 /html_error/403.html;
    error_page 404 /html_error/404.html;
    error_page 405 /html_error/405.html;
    error_page 408 /html_error/408.html;
    error_page 411 /html_error/411.html;
    error_page 413 /html_error/413.html;
    error_page 415 /html_error/415.html;
    error_page 500 /html_error/500.html;
    error_page 501 /html_error/501.html;
    error_page 502 /html_error/502.html;
    error_page 504 /html_error/504.html;
    error_page 505 /html_error/505.html;

    location / {
        root ./www;
        index index.html;
        allow_methods GET POST DELETE;
    }
    location /html_error/ {
        root ./www;
    }
    location /images/ {
        root ./www;
        client_max_body_size 1k;
        autoindex on;
    }
    location /cgi-bin/ {
        root ./www;
        cgi .py;
        cgi .sh;
    }
    location /upload/ {
        client_max_body_size 500K;
        root ./www;
        autoindex on;
        allow_methods GET POST DELETE;
    }
    location /redirection/ {
        return 301 https://42.fr/en/homepage/;
    }
    location /readonly/ {
        root ./www;
        allow_methods GET;
    }
    location /oldplace/ {
        return 302 /newplace/;
    }
    location /newplace/ {
        root ./www;
        index index.html;
        allow_methods GET;
    }
}

server {
     listen 8090;
     server_name backup.local;
     root /www/;
 }
